//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public System.DateTime SysCreatDate { get; set; }
        public int Factory { get; set; }
        public string EmployeeNum { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> StartDay { get; set; }
        public Nullable<System.DateTime> EndDay { get; set; }
        public Nullable<int> Status { get; set; }
        public int PhoneManufactory { get; set; }
        public int PhoneType { get; set; }
        public Nullable<System.DateTime> LastSendApp { get; set; }
        public string MainAreaPhone { get; set; }
        public string MainPhone { get; set; }
        public string SecondAreaPhone { get; set; }
        public string SecondPhone { get; set; }
        public Nullable<System.Guid> EmployeeKey { get; set; }
        public string Mail { get; set; }
        public Nullable<int> CustomerLinkDistanceThreshold { get; set; }
        public Nullable<int> DefultClientParamMode { get; set; }
    }
}
